from copy import deepcopy
import random


REBIRTH_CARD_CATALOG = [
    {
        "id": "ember_vowblade",
        "name": "Ember Vowblade",
        "element": "Fire",
        "archetype": "Oath Weapon",
        "rarity": "rare",
        "cost": 2,
        "attack": 6,
        "guard": 1,
        "ambition": 1,
        "text": "A blade that remembers every promise made in heat.",
        "role": "Striker",
        "model_key": "active_card_frame",
        "fx_key": "strike_fx",
    },
    {
        "id": "tideglass_oracle",
        "name": "Tideglass Oracle",
        "element": "Water",
        "archetype": "Mirror Seer",
        "rarity": "uncommon",
        "cost": 1,
        "attack": 3,
        "guard": 2,
        "ambition": 2,
        "text": "Reads the next wound in a reflection that has not formed.",
        "role": "Focus",
        "model_key": "active_card_frame",
        "fx_key": "focus_fx",
    },
    {
        "id": "ironroot_sentinel",
        "name": "Ironroot Sentinel",
        "element": "Earth",
        "archetype": "Living Bulwark",
        "rarity": "common",
        "cost": 2,
        "attack": 3,
        "guard": 5,
        "ambition": 0,
        "text": "A rooted oath with enough iron to refuse the sky.",
        "role": "Guardian",
        "model_key": "active_card_frame",
        "fx_key": "guard_fx",
    },
    {
        "id": "neon_wraith",
        "name": "Neon Wraith",
        "element": "Shadow",
        "archetype": "Afterimage",
        "rarity": "rare",
        "cost": 3,
        "attack": 5,
        "guard": 1,
        "ambition": 2,
        "text": "It cuts where the eye expected light to be.",
        "role": "Disruptor",
        "model_key": "active_card_frame",
        "fx_key": "strike_fx",
    },
    {
        "id": "solar_oathkeeper",
        "name": "Solar Oathkeeper",
        "element": "Light",
        "archetype": "Crown Guard",
        "rarity": "rare",
        "cost": 3,
        "attack": 4,
        "guard": 4,
        "ambition": 1,
        "text": "Carries dawn like a verdict, not a blessing.",
        "role": "Guardian",
        "model_key": "active_card_frame",
        "fx_key": "guard_fx",
    },
    {
        "id": "null_circuit",
        "name": "Null Circuit",
        "element": "Tech",
        "archetype": "Dead Protocol",
        "rarity": "uncommon",
        "cost": 1,
        "attack": 2,
        "guard": 3,
        "ambition": 2,
        "text": "A machine prayer that cancels fear before it becomes motion.",
        "role": "Disruptor",
        "model_key": "active_card_frame",
        "fx_key": "ambition_fx",
    },
    {
        "id": "ashen_duelist",
        "name": "Ashen Duelist",
        "element": "Fire",
        "archetype": "Last Blade",
        "rarity": "common",
        "cost": 1,
        "attack": 4,
        "guard": 1,
        "ambition": 1,
        "text": "Never draws first. Never needs to draw twice.",
        "role": "Striker",
        "model_key": "active_card_frame",
        "fx_key": "strike_fx",
    },
    {
        "id": "deepwell_monk",
        "name": "Deepwell Monk",
        "element": "Water",
        "archetype": "Silent Vessel",
        "rarity": "common",
        "cost": 1,
        "attack": 2,
        "guard": 2,
        "ambition": 3,
        "text": "The quietest will in the room is often the deepest.",
        "role": "Focus",
        "model_key": "active_card_frame",
        "fx_key": "focus_fx",
    },
    {
        "id": "obsidian_fox",
        "name": "Obsidian Fox",
        "element": "Shadow",
        "archetype": "False Trail",
        "rarity": "uncommon",
        "cost": 2,
        "attack": 4,
        "guard": 2,
        "ambition": 2,
        "text": "A grin in the dark is still a map.",
        "role": "Disruptor",
        "model_key": "active_card_frame",
        "fx_key": "strike_fx",
    },
    {
        "id": "aurora_myrmidon",
        "name": "Aurora Myrmidon",
        "element": "Light",
        "archetype": "Prism Soldier",
        "rarity": "common",
        "cost": 2,
        "attack": 4,
        "guard": 3,
        "ambition": 1,
        "text": "Disciplined light, sharpened until it becomes command.",
        "role": "Guardian",
        "model_key": "active_card_frame",
        "fx_key": "guard_fx",
    },
    {
        "id": "static_ronin",
        "name": "Static Ronin",
        "element": "Tech",
        "archetype": "Signal Blade",
        "rarity": "rare",
        "cost": 3,
        "attack": 6,
        "guard": 0,
        "ambition": 2,
        "text": "A wandering strike broadcast one heartbeat early.",
        "role": "Striker",
        "model_key": "active_card_frame",
        "fx_key": "strike_fx",
    },
    {
        "id": "verdant_colossus",
        "name": "Verdant Colossus",
        "element": "Earth",
        "archetype": "Worldroot Titan",
        "rarity": "legendary",
        "cost": 4,
        "attack": 5,
        "guard": 6,
        "ambition": 0,
        "text": "The arena bends around it like soil around a seed.",
        "role": "Guardian",
        "model_key": "active_card_frame",
        "fx_key": "guard_fx",
    },
    {
        "id": "cinder_saint",
        "name": "Cinder Saint",
        "element": "Fire",
        "archetype": "Ash Choir",
        "rarity": "uncommon",
        "cost": 2,
        "attack": 5,
        "guard": 2,
        "ambition": 1,
        "text": "Blesses the duel by burning hesitation out of it.",
        "role": "Striker",
        "model_key": "active_card_frame",
        "fx_key": "strike_fx",
    },
    {
        "id": "helios_breaker",
        "name": "Helios Breaker",
        "element": "Light",
        "archetype": "Sun Verdict",
        "rarity": "rare",
        "cost": 3,
        "attack": 6,
        "guard": 2,
        "ambition": 1,
        "text": "A clean line of light with no room for retreat.",
        "role": "Striker",
        "model_key": "active_card_frame",
        "fx_key": "strike_fx",
    },
    {
        "id": "glassreef_bulwark",
        "name": "Glassreef Bulwark",
        "element": "Water",
        "archetype": "Reef Bastion",
        "rarity": "uncommon",
        "cost": 2,
        "attack": 2,
        "guard": 6,
        "ambition": 1,
        "text": "Transparent until the strike breaks itself against it.",
        "role": "Guardian",
        "model_key": "active_card_frame",
        "fx_key": "guard_fx",
    },
    {
        "id": "rootscript_hermit",
        "name": "Rootscript Hermit",
        "element": "Earth",
        "archetype": "Buried Lexicon",
        "rarity": "common",
        "cost": 1,
        "attack": 2,
        "guard": 4,
        "ambition": 2,
        "text": "Writes patient power in a language the arena can feel.",
        "role": "Focus",
        "model_key": "active_card_frame",
        "fx_key": "focus_fx",
    },
    {
        "id": "black_neon_magistrate",
        "name": "Black Neon Magistrate",
        "element": "Shadow",
        "archetype": "Night Court",
        "rarity": "rare",
        "cost": 3,
        "attack": 4,
        "guard": 2,
        "ambition": 3,
        "text": "Rules against certainty and collects the silence afterward.",
        "role": "Disruptor",
        "model_key": "active_card_frame",
        "fx_key": "ambition_fx",
    },
    {
        "id": "pulsewire_savant",
        "name": "Pulsewire Savant",
        "element": "Tech",
        "archetype": "Living Circuit",
        "rarity": "uncommon",
        "cost": 2,
        "attack": 3,
        "guard": 3,
        "ambition": 3,
        "text": "Turns panic into pattern, then pattern into command.",
        "role": "Focus",
        "model_key": "active_card_frame",
        "fx_key": "ambition_fx",
    },
]


def get_rebirth_catalog():
    return deepcopy(REBIRTH_CARD_CATALOG)


def get_rebirth_card(card_id):
    for card in REBIRTH_CARD_CATALOG:
        if card["id"] == card_id:
            return deepcopy(card)
    return None


def build_rebirth_deck(seed=None):
    deck = get_rebirth_catalog()
    random.Random(seed).shuffle(deck)
    return deck
