#!/usr/bin/env python3
from pathlib import Path
import subprocess
import sys
import urllib.error
import urllib.request


PROJECT_ROOT = Path(__file__).resolve().parents[2]
REPORT_PATH = PROJECT_ROOT / "docs" / "RC_V8_ASCENSION_RELEASE_MATRIX.md"


def run_command(command):
    result = subprocess.run(command, cwd=PROJECT_ROOT, text=True, capture_output=True)
    return {
        "command": " ".join(command),
        "returncode": result.returncode,
        "stdout": result.stdout[-4000:],
        "stderr": result.stderr[-4000:],
        "ok": result.returncode == 0,
    }


def curl_smoke():
    targets = [
        "http://127.0.0.1:5087/training",
        "http://127.0.0.1:5087/training-legacy",
        "http://127.0.0.1:5087/collection-ascension",
        "http://127.0.0.1:5087/deck-builder-ascension",
    ]
    results = []
    for target in targets:
        try:
            with urllib.request.urlopen(target, timeout=1.5) as response:
                results.append({"url": target, "status": response.status, "ok": response.status == 200})
        except (urllib.error.URLError, TimeoutError, OSError) as error:
            results.append({"url": target, "status": "unavailable", "ok": None, "error": type(error).__name__})
    return results


def build_report(results, smoke):
    lines = [
        "# RC V8 Ascension Release Matrix",
        "",
        "## Command Results",
    ]
    for result in results:
        status = "PASS" if result["ok"] else "FAIL"
        lines.append(f"- {status}: `{result['command']}`")
        if not result["ok"]:
            lines.append("```")
            lines.append(result["stdout"])
            lines.append(result["stderr"])
            lines.append("```")

    lines.extend(["", "## Local Curl Smoke"])
    for item in smoke:
        if item["ok"] is True:
            lines.append(f"- PASS: {item['url']} returned {item['status']}")
        elif item["ok"] is None:
            lines.append(f"- SKIP: {item['url']} unavailable locally ({item.get('error')})")
        else:
            lines.append(f"- FAIL: {item['url']} returned {item['status']}")

    lines.extend(
        [
            "",
            "## Summary",
            "The release matrix is generated by `tools/qa/qa_ascension_release_matrix.py`.",
        ]
    )
    return "\n".join(lines) + "\n"


def main():
    qa_scripts = sorted(
        path
        for path in (PROJECT_ROOT / "tools" / "qa").glob("qa_ascension_*.py")
        if path.name != "qa_ascension_release_matrix.py"
    )
    commands = [
        [sys.executable, "-m", "pytest", "-q"],
        [
            sys.executable,
            "-m",
            "py_compile",
            "services/ascension_cards.py",
            "services/ascension_engine.py",
            "services/ascension_bot.py",
            "services/ascension_payloads.py",
            "services/ascension_progression.py",
        ],
        ["node", "--check", "static/js/ambitionz_ascension.js"],
    ]
    commands.extend([[sys.executable, str(path.relative_to(PROJECT_ROOT))] for path in qa_scripts])

    results = [run_command(command) for command in commands]
    smoke = curl_smoke()
    REPORT_PATH.write_text(build_report(results, smoke), encoding="utf-8")

    failed = [result for result in results if not result["ok"]]
    if failed:
        print(REPORT_PATH.read_text(encoding="utf-8"))
        raise SystemExit(1)
    print("PASS ascension_release_matrix")


if __name__ == "__main__":
    main()
