#!/usr/bin/env python3
import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from services.rebirth_balance import simulate_balance


def pct(value):
    return f"{float(value) * 100:.1f}%"


def table(headers, rows):
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(item) for item in row) + " |")
    return "\n".join(lines)


def render_report(payload):
    summary = payload["summary"]
    lines = [
        "# Rebirth Balance Report",
        "",
        "Generated by `tools/rebirth_balance_report.py` using the active Ambitionz Rebirth engine.",
        "",
        "## Summary",
        "",
        table(
            ["Matches", "Player WR", "Bot WR", "Unfinished", "Avg Turns"],
            [
                [
                    payload["matches"],
                    pct(summary["player_win_rate"]),
                    pct(summary["bot_win_rate"]),
                    pct(summary["unfinished_rate"]),
                    summary["average_turns"],
                ]
            ],
        ),
        "",
        "## Bot Profiles",
        "",
        table(
            ["Profile", "Matches", "Player WR", "Bot WR", "Avg Turns"],
            [
                [
                    row["name"],
                    row["matches"],
                    pct(row["player_win_rate"]),
                    pct(row["bot_win_rate"]),
                    row["average_turns"],
                ]
                for row in payload["profile_results"]
            ],
        ),
        "",
        "## Card Impact",
        "",
        table(
            ["Card", "Plays", "WR", "Avg Damage", "Evolve Rate", "Dead Rate", "Flags"],
            [
                [
                    row["name"],
                    row["plays"],
                    pct(row["win_rate"]),
                    row["avg_damage"],
                    pct(row["evolve_rate"]),
                    pct(row["dead_card_rate"]),
                    ", ".join(row["flags"]) or "ok",
                ]
                for row in payload["card_stats"]
            ],
        ),
        "",
        "## Ability Impact",
        "",
        table(
            ["Ability", "Plays", "WR", "Avg Damage"],
            [
                [row["name"], row["plays"], pct(row["win_rate"]), row["avg_damage"]]
                for row in payload["ability_stats"]
            ],
        ),
        "",
        "## Evolution Usage",
        "",
        table(
            ["Card", "Count"],
            [[row["card_id"], row["count"]] for row in payload["evolution_usage"]] or [["none", 0]],
        ),
        "",
        "## Notes",
        "",
        f"- Policy: {payload['bot_tuning']['policy']}",
        f"- Status: {payload['bot_tuning']['status']}",
        "- This is a deterministic Season 0 lab, not a production analytics substitute.",
        "- Real production balancing still needs live telemetry, match history sampling and visual QA.",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate an Ambitionz Rebirth balance report.")
    parser.add_argument("--matches", type=int, default=120)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    payload = simulate_balance(matches=args.matches)
    report = render_report(payload)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report, encoding="utf-8")
    print(report)


if __name__ == "__main__":
    main()
